name: Build docker image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_and_push_docker_image:
    name: Build and push docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get latest version tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .docker
          platforms: linux/amd64
          push: true
          tags: |
            krzysztofkortas/cppenv-trunk:latest
            krzysztofkortas/cppenv-trunk:${{ steps.previoustag.outputs.tag }}
